### ISSUE TITLE
I'm getting some unknown characters

### ISSUE THREAD

**Issue by pulketo** [wapmorgan/Mp3Info#12]
I'm getting some unknown characters on terminal:
php i.php
[
![mp3](https://user-images.githubusercontent.com/337881/45392735-5f44fa00-b5ee-11e8-9f91-d8d34b8ab3e3.jpg)
](url)

they display correctly thru iconv...
php i.php | iconv -f ISO-8859-1 -t utf-8
![mp3-2](https://user-images.githubusercontent.com/337881/45392777-88fe2100-b5ee-11e8-9aa4-04f24de9af19.jpg)

**Comment by wapmorgan** [comment]
Check it again

**Comment by wapmorgan** [comment]
@pulketo Pls provide sample file
