### ISSUE TITLE
Cannot determine codecVersion

### ISSUE THREAD

**Issue by swilczynski** [wapmorgan/Mp3Info#14]
Hello,

I get following error when trying to load mp3 file

`Notice: Undefined index: in /var/www/vendor/wapmorgan/mp3info/src/Mp3Info.php on line 270
Notice: Undefined index: in /var/www/vendor/wapmorgan/mp3info/src/Mp3Info.php on line 271
Notice: Undefined variable: offset in /var/www/vendor/wapmorgan/mp3info/src/Mp3Info.php on line 286
Warning: Division by zero in /var/www/vendor/wapmorgan/mp3info/src/Mp3Info.php on line 300
Warning: fseek() expects parameter 2 to be integer, float given in /var/www/vendor/wapmorgan/mp3info/src/Mp3Info.php on line 302
Warning: Division by zero in /var/www/vendor/wapmorgan/mp3info/src/Mp3Info.php on line 226`

As far as I was able to debug the issue I saw that $headerBytes[1] equals 227 in my mp3 file and 227 >> 3 & 0b11 = 0 and there is no option for this.

Unfortunately I am not experienced with bitwise operations and mp3 specifications, maybe this is something you could look into.

I can provide mp3 file in PM when requested

**Comment by wapmorgan** [comment]
> I can provide mp3 file in PM when requested

Yes, provide it to fix.

**Comment by swilczynski** [comment]
Sorry I opened this issue half year ago, I don't have this file anymore
