### ISSUE TITLE
Can't open remote file

### ISSUE THREAD

**Issue by istratos** [wapmorgan/Mp3Info#19]
This library is pretty good at what it does, unfortunately it seems to not support remote urls. My app uploads to S3, so giving it an absolute url it still says the file is not found. It would be great if you included remote files support, as storing objects in the cloud is more common nowadays!

**Comment by wapmorgan** [comment]
Need a sample of file to test

**Comment by wapmorgan** [comment]
0.0.7 version supports remote files

**Comment by IllesAprod** [comment]
@wapmorgan Mp3Info giving me File is not present when trying remote (s3 based) files.

Example url: https://reedioo.s3.eu-central-1.amazonaws.com/synced/%2200098009cc463acf2dd59b61cdcfa6a6%22.mp3

Example code:
```
            $audio = new Mp3Info('https://reedioo.s3.eu-central-1.amazonaws.com/synced/%2200098009cc463acf2dd59b61cdcfa6a6%22.mp3');
            dd($audio->duration);
```
