### ISSUE TITLE
File not present error when trying remote file from S3

### ISSUE THREAD

**Issue by IllesAprod** [wapmorgan/Mp3Info#21]
Mp3Info giving me File is not present when trying remote (s3 based) files.

Example url: https://reedioo.s3.eu-central-1.amazonaws.com/synced/%2200098009cc463acf2dd59b61cdcfa6a6%22.mp3

Example code:
```
            $audio = new Mp3Info('https://reedioo.s3.eu-central-1.amazonaws.com/synced/%2200098009cc463acf2dd59b61cdcfa6a6%22.mp3');
            dd($audio->duration);
```

_Originally posted by @IllesAprod in https://github.com/wapmorgan/Mp3Info/issues/19#issuecomment-949428674_

**Comment by mnarbash** [comment]
i have same problem

**Comment by hayjay** [comment]
@paurakhsharma @wapmorgan please merge this PR [#22](https://github.com/wapmorgan/Mp3Info/pull/22), it basically solves the url issue.

Thanks

**Comment by wapmorgan** [comment]
@hayjay Merged PR
