### ISSUE TITLE
mb_convert_encoding(): Passing null to parameter #1 ($string) of type array|string is deprecated in Mp3Info.php on line 704

### ISSUE THREAD

**Issue by kesselb** [wapmorgan/Mp3Info#29]
Hi,

I see the following a deprecation warning with our test file: https://github.com/nextcloud/server/blob/master/tests/data/testimage.mp3

`PHP Deprecated:  mb_convert_encoding(): Passing null to parameter #1 ($string) of type array|string is deprecated in Mp3Info.php on line 704`

https://github.com/wapmorgan/Mp3Info/blob/a28101d523d271e52c43ff0854e55cc3f110d2de/src/Mp3Info.php#L690

Changing ` $short_description = null;` to ` $short_description = '';` fixes the error for me. 
I know too little about ID3v2 to judge it that's correct.

**Comment by wapmorgan** [comment]
Try 0.1.0 version

**Comment by kesselb** [comment]
Thank you :+1: 

No more deprecation warnings with our test file :tada:

**Comment by painbaker** [comment]
Still passing null for id3v2.4.0:

https://github.com/wapmorgan/Mp3Info/blob/d749cdd86201ecde740af9863ca1c940c456893e/src/Mp3Info.php#L890

And it is also possible for ```$actual_text```:

https://github.com/wapmorgan/Mp3Info/blob/d749cdd86201ecde740af9863ca1c940c456893e/src/Mp3Info.php#L696-L702
https://github.com/wapmorgan/Mp3Info/blob/d749cdd86201ecde740af9863ca1c940c456893e/src/Mp3Info.php#L898-L902
