### ISSUE TITLE
Can't retrieve metadata

### ISSUE THREAD

**Issue by Lecodeurenretard** [wapmorgan/Mp3Info#33]
Hello,
I am working on a server and I wrote a script that fetch tags of a mp3 file, the issue is once the `new Mp3Info($path);` , the properties: _'tags'_, _'tags1'_ and _'tags2'_ are empty arrays ( I know it from` var_dump()`).

I tried to switch from the URL to the path on the server but it doesn't change anything.

edit: I also checked the metadatas with the cmd line.

**Comment by wapmorgan** [comment]
Provide a sample file to investigate

**Comment by Lecodeurenretard** [comment]
The music file: [You-May-Call-Me-Father.zip](https://github.com/wapmorgan/Mp3Info/files/14156730/You-May-Call-Me-Father.zip)

**The command line result:**
![Screenshot cmd line](https://github.com/wapmorgan/Mp3Info/assets/111014383/1e385e67-5573-4cd5-b90b-304d1c1ae827)



**The ``var_dump()`` result:**
![Screenshot var dump](https://github.com/wapmorgan/Mp3Info/assets/111014383/7746b25b-54ea-461c-8691-c94766bb47c7)

**Comment by wapmorgan** [comment]
```php
// If you need parse tags, you should set 2nd argument this way:
$audio = new Mp3Info('./audio.mp3', true);
```

**Comment by Lecodeurenretard** [comment]
Oh thank you!
English is not my first language so I didn't understood the doc well.
