### ISSUE TITLE
Should be first frame header?

### ISSUE THREAD

**Issue by jpmurray** [wapmorgan/Mp3Info#7]
Hello,

Currently building myself a tool in my spare time, and I've been using Mp3Info for about a week now and, two days ago, I started to get, coming from `readFirstFrame()`: `At 0(0) should be the first frame header!`.

Now, the thing that changed: I formatted my laptop ! I'm wondering if there is any dependencies outside of PHP that I might have missed that influence this?

**Comment by wapmorgan** [comment]
Ok, @jpmurray check it now with latest updates (**0.0.3**).

**Comment by wizwizcao** [comment]
Get a similar alert ```At 4121(1019) should be the first frame header!```
There could be some noise data at the header. One suggestion is to update the code from 
```
if (array_unique($headerBytes) === [0]) {
```
to
```
if (($headerBytes[0] & 0xFF) != 0xFF || array_unique($headerBytes) === [0]) {
```
Located in Mp3Info.php, line 245. I am ok now.

**Comment by wapmorgan** [comment]
Updated **dev-master**, check it out.

**Comment by wapmorgan** [comment]
@wizwizcao check out **dev-master** branch

**Comment by wizwizcao** [comment]
It works.

**Comment by wapmorgan** [comment]
OK, I'll release soon.
