### ISSUE TITLE
const FRAME_SYNC missing

### ISSUE THREAD

**Issue by kainabel** [wapmorgan/Mp3Info#9]
e.g. for line 27:
`const FRAME_SYNC = 0xffe0; // bit mask`

and
`return ($raw == self::TAG2_SYNC || (self::FRAME_SYNC == (unpack('n*', $raw)[1] & self::FRAME_SYNC)));`
as a replacement for https://github.com/wapmorgan/Mp3Info/blob/1f083faf60401a1e833309ba48147123c507c4a4/src/Mp3Info.php#L669

**Comment by wapmorgan** [comment]
Fixed

**Comment by t0mmie** [comment]
@wapmorgan do you have a new release planned with this fix?

**Comment by wapmorgan** [comment]
@t0mmie  Released
